config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Rails.application.routes.draw do
  resources :contacts
  resources :contact_imports do
    resources :contacts, only: [:index]
    resources :contact_faileds, only: [:index]
  end

  devise_for :users

  root to: 'contact_imports#index'
  mount Sidekiq::Web => '/sidekiq'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
# frozen_string_literal: true

require 'bcrypt'

class Contact < ApplicationRecord
  VALID_DATE_REGEX = /\A(\d{4}-\d{2}-\d{2})|(\d{8})\z/.freeze
  VALID_PHONE_REGEX = /\A(\(\+\d{2}\)( \d{3}){2}( \d{2}){2})|(\(\+\d{2}\) (\d{3}-){2}\d{2}-\d{2})\z/.freeze
  VALID_NAME_REGEX = /\A[0-9a-zA-Z -]+\z/.freeze

  belongs_to :user
  belongs_to :contact_import

  validates :email, email: true
  validates :email, presence: true, uniqueness: { scope: :user_id }, unless: -> { errors.include?(:email) }
  validates :name, format: { with: VALID_NAME_REGEX }, presence: true
  validates :date_of_birth, presence: true
  validates :phone, format: { with: VALID_PHONE_REGEX }, presence: true
  validates :address, presence: true

  validate :credit_card_valid?

  def date_of_birth=(value)
    return unless value.is_a?(Time) || value =~ VALID_DATE_REGEX

    super(value)
  end

  def credit_card=(value)
    detector = CreditCardValidations::Detector.new(value)
    return unless detector.valid?

    self.credit_card_hash = BCrypt::Password.create(value)
    self.credit_card_issuer = detector.brand
    self.credit_card_last = value.gsub(/\D/, '')[-4..]
  end

  private

  def credit_card_valid?
    errors.add(:credit_card, 'is invalid') if credit_card_hash.blank?
  end
end

app/models/contact_failed.rb
# frozen_string_literal: true

class ContactFailed < ApplicationRecord
  belongs_to :contact_import
  belongs_to :user
end

app/models/contact_import.rb
# frozen_string_literal: true

class ContactImport < ApplicationRecord
  MAPPING_FIELDS = %w[name date_of_birth phone address credit_card email].freeze
  enum status: { on_hold: 0, processing: 1, failed: 2, finished: 3 }, _prefix: true, _default: :on_hold

  belongs_to :user
  has_many :contacts, dependent: :nullify
  has_many :contact_faileds, dependent: :delete_all

  has_one_attached :contacts_file

  validates :contacts_file, presence: true, blob: { content_type: ['text/csv'], size_range: 1..(10.megabytes) }
  validates :fields_order, presence: true
  validate :fields_order_valid?

  after_create :import_contacts_async!

  def check_progress!
    ContactImportProgressChecker.new(self, enqueue: false).call
  end

  def import_contacts_async!
    ContactsImporterWorker.perform_async(id)
  end

  private

  def fields_order_valid?
    return if fields_order.blank?
    return if (fields_order & MAPPING_FIELDS).size == MAPPING_FIELDS.size && fields_order.size == fields_order.uniq.size

    errors.add(:fields_order, 'is invalid')
  end
end

app/models/contact_import_progress_checker.rb
# frozen_string_literal: true

class ContactImportProgressChecker
  def initialize(contact_import, enqueue: false, previous_total_processed: 0, attempts: 0)
    @contact_import = contact_import
    @enqueue = enqueue
    @previous_total_processed = previous_total_processed
    @attempts = attempts
  end

  def call
    return unless @contact_import.status_processing?

    check_progress!
  end

  private

  def check_progress!
    return enqueue_job if total_processed < @contact_import.total_rows

    if total_imported.positive?
      @contact_import.status_finished!
    else
      @contact_import.status_failed!
    end
  end

  def enqueue_job
    return unless @enqueue

    if @previous_total_processed == total_processed
      @attempts += 1
    else
      @attempts = 0
    end

    CheckImportProgressWorker.perform_in(2.seconds, @contact_import.id, total_processed, @attempts)
  end

  def total_processed
    total_imported + total_failed
  end

  def total_imported
    @total_imported ||= @contact_import.contacts.count
  end

  def total_failed
    @total_failed ||= @contact_import.contact_faileds.count
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contact_imports, dependent: :delete_all
  has_many :contacts, dependent: :delete_all
  has_many :contact_faileds, dependent: :delete_all
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/contact_faileds_controller.rb
# frozen_string_literal: true

class ContactFailedsController < ApplicationController
  def index
    @contact_import = current_user.contact_imports.find(params[:contact_import_id])
    @contact_faileds = @contact_import.contact_faileds.order(:line_number).page(params[:page])
  end
end

app/controllers/contact_imports_controller.rb
# frozen_string_literal: true

class ContactImportsController < ApplicationController
  def index
    @contact_imports = current_user.contact_imports.order(:created_at).page(params[:page])
    ActiveRecord::Precounter.new(@contact_imports).precount(:contacts)
    ActiveRecord::Precounter.new(@contact_imports).precount(:contact_faileds)
  end

  def show
    @contact_import = current_user.contact_imports.find(params[:id])
  end

  def new
    @contact_import = current_user.contact_imports.build
  end

  def create
    @contact_import = current_user.contact_imports.build(contact_import_params)
    if @contact_import.save
      redirect_to @contact_import
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def contact_import_params
    params.require(:contact_import).permit(:contacts_file, fields_order: [])
  end
end

app/controllers/contacts_controller.rb
# frozen_string_literal: true

class ContactsController < ApplicationController
  def index
    @contacts = current_user.contacts.order(:created_at).page(params[:page])

    return unless params[:contact_import_id]

    @contact_import = current_user.contact_imports.find(params[:contact_import_id])
    @contacts = @contacts.where(contact_import: @contact_import)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/contact_faileds/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Listing failed contacts</h1>

      <p>Contact import #<%= link_to(@contact_import.id, contact_import_path(@contact_import)) %></p>

      <table class="table">
        <thead>
          <tr>
            <th>Line number</th>
            <th>Reasons</th>
          </tr>
        </thead>

        <tbody>
          <% @contact_faileds.each do |contact_failed| %>
            <tr>
              <td><%= contact_failed.line_number %></td>
              <td><%= contact_failed.messages.join('; ') %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= paginate @contact_faileds, theme: 'bootstrap-5' %>
    </div>
  </div>
</div>

app/views/contact_imports/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Listing Imports</h1>

      <%= link_to('New import', new_contact_import_path, class: 'btn btn-success mt-3 mb-3') %>

      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Imported at</th>
            <th>Status</th>
            <th>Total rows</th>
            <th>Success</th>
            <th>Failed</th>
            <th colspan="1"></th>
          </tr>
        </thead>

        <tbody>
          <% @contact_imports.each do |contact_import| %>
            <tr>
              <td><%= contact_import.id %></td>
              <td><%= contact_import.created_at.iso8601 %></td>
              <td><%= contact_import.status %></td>
              <td><%= contact_import.total_rows %></td>
              <td><%= contact_import.contacts_count %></td>
              <td><%= contact_import.contact_faileds_count %></td>
              <td><%= link_to "Show", contact_import %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= paginate @contact_imports, theme: 'bootstrap-5' %>
    </div>
  </div>
</div>

app/views/contact_imports/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>New Import</h1>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= form_for @contact_import, html: { class: 'form mt-3' } do |f| %>
        <% if @contact_import.errors.any? %>
          <div class="alert alert-danger" role="alert">
            <ul class="mb-0">
              <% @contact_import.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <% ContactImport::MAPPING_FIELDS.each.with_index do |field, index| %>
          <div class="mb-3">
            <label class="form-label"><%= "Select field to match #{index + 1} column" %></label>
            <%= f.select(:fields_order, ContactImport::MAPPING_FIELDS, { selected: @contact_import.fields_order.try(:[], index) }, { class: 'form-select', name: "contact_import[fields_order][]" }) %>
          </div>
        <% end %>

        <%= f.file_field :contacts_file, { class: 'form-control mb-3' } %>
        <%= f.submit "Submit", { class: 'btn btn-success' } %>
      <% end %>
    </div>
  </div>
</div>

app/views/contact_imports/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Import #<%= @contact_import.id %></h1>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col">
      <dl>
        <dt>Status</dt>
        <dd><%= @contact_import.status %></dd>
      </dl>
    </div>
    <div class="col">
      <dl>
        <dt>Total imported with success</dt>
        <dd><%= link_to(@contact_import.contacts.count, contact_import_contacts_path(@contact_import)) %></dd>
      </dl>
    </div>
    <div class="col">
      <dl>
        <dt>Total imported with failure</dt>
        <dd><%= link_to(@contact_import.contact_faileds.count, contact_import_contact_faileds_path(@contact_import)) %></dd>
      </dl>
    </div>
  </div>
</div>

app/views/contacts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <h1>Listing Contacts</h1>

      <% if @contact_import %>
        <p>Contact import #<%= link_to(@contact_import.id, contact_import_path(@contact_import)) %></p>
      <% end %>

      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th>Date of birth</th>
            <th>Phone</th>
            <th>Address</th>
            <th>Card Issuer</th>
            <th>Last digits</th>
            <th>Email</th>
          </tr>
        </thead>

        <tbody>
          <% @contacts.each do |contact| %>
            <tr>
              <td><%= contact.id %></td>
              <td><%= contact.name %></td>
              <td><%= contact.date_of_birth.strftime('%Y %B %e') %></td>
              <td><%= contact.phone %></td>
              <td><%= contact.address %></td>
              <td><%= contact.credit_card_issuer %></td>
              <td><%= contact.credit_card_last %></td>
              <td><%= contact.email %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= paginate @contacts, theme: 'bootstrap-5' %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ContactsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <%= link_to 'Imports', contact_imports_path, class: "nav-link #{controller_name == 'contact_imports' ? 'active' : ''}" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Contacts', contacts_path, class: "nav-link #{controller_name == 'contacts' ? 'active' : ''}" %>
          </li>
        </ul>
        <span class="navbar-text">
          <%= link_to "Logout", destroy_user_session_path, method: :delete , class: 'text-decoration-none' %>
        </span>
      </div>
    </div>
  </nav>
<% end %>